# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8fa26d1c9f7ac9132353ec928b1f46dea145e000bfc465b073229a48f1d3fc387bec6ab9f386b765dcc36979c675e1a7584cad099c89a76f77f818aab80327

test:
  secret_key_base: 411b5b870c3a6ab35acef3636aba089a5ca5de09361eebd1e9370277671a7f51defe3cdc1a766657298801357797ca6058725edfd13c9ddb724d6daf47f22a51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
